CREATE DATABASE IF NOT EXISTS db;
use db;

CREATE TABLE IF NOT EXISTS `table` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `val` varchar(255) NULL DEFAULT NULL,
  `val` varchar(255) NULL DEFAULT NULL,
  `val` date NULL DEFAULT NULL,
  `val` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `val` int(4) UNSIGNED NOT NULL DEFAULT 0,
  `val` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`for`) REFERENCES table2(`field`)
);